"""merge_toma_work_snake_case

Revision ID: 4b426a21cb22
Revises: 7025a1405325
Create Date: 2026-01-11 18:34:07.051877

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4b426a21cb22'
down_revision: Union[str, None] = '7025a1405325'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('effects',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('effect_id', sa.Integer(), nullable=True),
    sa.Column('item_id', sa.Integer(), nullable=True),
    sa.Column('ad_base_dmg', sa.Float(), nullable=True),
    sa.Column('ap_base_dmg', sa.Float(), nullable=True),
    sa.Column('ad_ratio', sa.Float(), nullable=True),
    sa.Column('ap_ratio', sa.Float(), nullable=True),
    sa.Column('hp_ratio', sa.Float(), nullable=True),
    sa.Column('armor_ratio', sa.Float(), nullable=True),
    sa.Column('mr_ratio', sa.Float(), nullable=True),
    sa.Column('crit_ratio', sa.Float(), nullable=True),
    sa.Column('speed_ratio', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_effects_effect_id'), 'effects', ['effect_id'], unique=False)
    op.create_index(op.f('ix_effects_id'), 'effects', ['id'], unique=False)
    op.create_index(op.f('ix_effects_item_id'), 'effects', ['item_id'], unique=False)
    op.create_table('item_stats',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('item_id', sa.Integer(), nullable=True),
    sa.Column('hp', sa.Float(), nullable=True),
    sa.Column('ad', sa.Float(), nullable=True),
    sa.Column('ap', sa.Float(), nullable=True),
    sa.Column('adaptive_force', sa.Float(), nullable=True),
    sa.Column('armor', sa.Float(), nullable=True),
    sa.Column('magic_resist', sa.Float(), nullable=True),
    sa.Column('speed_flat', sa.Float(), nullable=True),
    sa.Column('crit_chance_percent', sa.Float(), nullable=True),
    sa.Column('life_steal_percent', sa.Float(), nullable=True),
    sa.Column('spell_vamp_percent', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_item_stats_id'), 'item_stats', ['id'], unique=False)
    op.create_index(op.f('ix_item_stats_item_id'), 'item_stats', ['item_id'], unique=False)
    op.create_table('player_stats',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('player_id', sa.Integer(), nullable=True),
    sa.Column('hp_flat', sa.Float(), nullable=True),
    sa.Column('hp_percent', sa.Float(), nullable=True),
    sa.Column('ad', sa.Float(), nullable=True),
    sa.Column('ap', sa.Float(), nullable=True),
    sa.Column('armor', sa.Float(), nullable=True),
    sa.Column('magic_resist', sa.Float(), nullable=True),
    sa.Column('speed_flat', sa.Float(), nullable=True),
    sa.Column('speed_percent', sa.Float(), nullable=True),
    sa.Column('crit_rate_percent', sa.Float(), nullable=True),
    sa.Column('penetration_flat', sa.Float(), nullable=True),
    sa.Column('penetration_percent', sa.Float(), nullable=True),
    sa.Column('final_damage_dealt_percent', sa.Float(), nullable=True),
    sa.Column('on_hit_damage_flat', sa.Float(), nullable=True),
    sa.Column('damage_reduction_percent', sa.Float(), nullable=True),
    sa.Column('damage_reduction_flat', sa.Float(), nullable=True),
    sa.Column('heal_shield_power_percent', sa.Float(), nullable=True),
    sa.Column('echo_gauge_percent', sa.Float(), nullable=True),
    sa.Column('berserk_stats_percent', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_player_stats_id'), 'player_stats', ['id'], unique=False)
    op.create_index(op.f('ix_player_stats_player_id'), 'player_stats', ['player_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_player_stats_player_id'), table_name='player_stats')
    op.drop_index(op.f('ix_player_stats_id'), table_name='player_stats')
    op.drop_table('player_stats')
    op.drop_index(op.f('ix_item_stats_item_id'), table_name='item_stats')
    op.drop_index(op.f('ix_item_stats_id'), table_name='item_stats')
    op.drop_table('item_stats')
    op.drop_index(op.f('ix_effects_item_id'), table_name='effects')
    op.drop_index(op.f('ix_effects_id'), table_name='effects')
    op.drop_index(op.f('ix_effects_effect_id'), table_name='effects')
    op.drop_table('effects')
    # ### end Alembic commands ###
