"""add combat tables

Revision ID: 4cf0a9f6aece
Revises: 4b426a21cb22
Create Date: 2026-02-22 21:06:21.211002

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4cf0a9f6aece'
down_revision: Union[str, None] = '4b426a21cb22'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('combat_sessions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('player_id', sa.Integer(), nullable=False),
    sa.Column('monster_id', sa.Integer(), nullable=False),
    sa.Column('monster_level', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'IN_PROGRESS', 'PLAYER_TURN', 'MONSTER_TURN', 'VICTORY', 'DEFEAT', 'ABANDONED', name='combat_status_enum', create_constraint=True), nullable=False),
    sa.Column('turn_count', sa.Integer(), nullable=True),
    sa.Column('current_turn_entity', sa.String(length=20), nullable=True),
    sa.Column('player_current_hp', sa.Integer(), nullable=False),
    sa.Column('player_max_hp', sa.Integer(), nullable=False),
    sa.Column('player_echo_current', sa.Integer(), nullable=True),
    sa.Column('player_echo_max', sa.Integer(), nullable=True),
    sa.Column('player_statuses', sa.JSON(), nullable=True),
    sa.Column('player_gauges', sa.JSON(), nullable=True),
    sa.Column('player_cds', sa.JSON(), nullable=True),
    sa.Column('monster_current_hp', sa.Integer(), nullable=False),
    sa.Column('monster_max_hp', sa.Integer(), nullable=False),
    sa.Column('monster_statuses', sa.JSON(), nullable=True),
    sa.Column('monster_cds', sa.JSON(), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('ended_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['monster_id'], ['monsters.monster_id'], ),
    sa.ForeignKeyConstraint(['player_id'], ['players.player_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_combat_sessions_id'), 'combat_sessions', ['id'], unique=False)
    op.create_index(op.f('ix_combat_sessions_player_id'), 'combat_sessions', ['player_id'], unique=False)
    op.create_table('combat_logs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('combat_session_id', sa.Integer(), nullable=False),
    sa.Column('turn', sa.Integer(), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['combat_session_id'], ['combat_sessions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_combat_logs_combat_session_id'), 'combat_logs', ['combat_session_id'], unique=False)
    op.create_index(op.f('ix_combat_logs_id'), 'combat_logs', ['id'], unique=False)
    op.create_table('combat_spell_cooldowns',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('combat_session_id', sa.Integer(), nullable=False),
    sa.Column('spell_code', sa.String(length=100), nullable=False),
    sa.Column('entity_id', sa.String(length=50), nullable=False),
    sa.Column('remaining_turns', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['combat_session_id'], ['combat_sessions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_combat_spell_cooldowns_id'), 'combat_spell_cooldowns', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_combat_spell_cooldowns_id'), table_name='combat_spell_cooldowns')
    op.drop_table('combat_spell_cooldowns')
    op.drop_index(op.f('ix_combat_logs_id'), table_name='combat_logs')
    op.drop_index(op.f('ix_combat_logs_combat_session_id'), table_name='combat_logs')
    op.drop_table('combat_logs')
    op.drop_index(op.f('ix_combat_sessions_player_id'), table_name='combat_sessions')
    op.drop_index(op.f('ix_combat_sessions_id'), table_name='combat_sessions')
    op.drop_table('combat_sessions')
    # ### end Alembic commands ###
