"""initial_migration

Revision ID: 7025a1405325
Revises: 
Create Date: 2026-01-11 17:35:12.148485

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7025a1405325'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('items',
    sa.Column('item_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('rarity', sa.String(length=50), nullable=True),
    sa.Column('item_type', sa.String(length=50), nullable=False),
    sa.Column('value', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('item_id')
    )
    op.create_index(op.f('ix_items_item_id'), 'items', ['item_id'], unique=False)
    op.create_table('monsters',
    sa.Column('monster_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('level', sa.Integer(), nullable=False),
    sa.Column('hp_max', sa.Integer(), nullable=False),
    sa.Column('attack_damage', sa.Integer(), nullable=False),
    sa.Column('reward_xp', sa.Integer(), nullable=False),
    sa.Column('reward_gold', sa.Integer(), nullable=False),
    sa.Column('metadata_props', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('monster_id'),
    sa.UniqueConstraint('name')
    )
    op.create_index(op.f('ix_monsters_monster_id'), 'monsters', ['monster_id'], unique=False)
    op.create_table('player_shop',
    sa.Column('player_shop_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.PrimaryKeyConstraint('player_shop_id')
    )
    op.create_index(op.f('ix_player_shop_player_shop_id'), 'player_shop', ['player_shop_id'], unique=False)
    op.create_table('quests',
    sa.Column('quest_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('quest_type', sa.Enum('Unique', 'Repeatable', name='quest_type_enum'), nullable=False),
    sa.Column('category', sa.Enum('MainStory', 'SideQuest', 'Event', 'Daily', 'Weekly', 'Monthly', name='quest_category_enum'), nullable=False),
    sa.Column('reward_xp', sa.Integer(), nullable=True),
    sa.Column('reward_gold', sa.Integer(), nullable=False),
    sa.Column('reward_chest', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('quest_id')
    )
    op.create_index(op.f('ix_quests_quest_id'), 'quests', ['quest_id'], unique=False)
    op.create_table('titles',
    sa.Column('title_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('title_name', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('title_id')
    )
    op.create_index(op.f('ix_titles_title_id'), 'titles', ['title_id'], unique=False)
    op.create_table('weapons',
    sa.Column('weapon_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('bonus_ad', sa.Integer(), nullable=True),
    sa.Column('bonus_ap', sa.Integer(), nullable=True),
    sa.Column('bonus_speed', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('weapon_id')
    )
    op.create_index(op.f('ix_weapons_weapon_id'), 'weapons', ['weapon_id'], unique=False)
    op.create_table('players',
    sa.Column('player_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('twitch_id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=50), nullable=False),
    sa.Column('level', sa.Integer(), nullable=True),
    sa.Column('gold', sa.Integer(), nullable=True),
    sa.Column('echo_current', sa.Integer(), nullable=True),
    sa.Column('echo_max', sa.Integer(), nullable=True),
    sa.Column('experience', sa.BigInteger(), nullable=True),
    sa.Column('health_points', sa.Integer(), nullable=True),
    sa.Column('attack_damage', sa.Integer(), nullable=True),
    sa.Column('ability_power', sa.Integer(), nullable=True),
    sa.Column('armor', sa.Integer(), nullable=True),
    sa.Column('magic_resistance', sa.Integer(), nullable=True),
    sa.Column('attack_speed', sa.Integer(), nullable=True),
    sa.Column('ability_haste', sa.Integer(), nullable=True),
    sa.Column('crit_chance', sa.Integer(), nullable=True),
    sa.Column('dodge', sa.Integer(), nullable=True),
    sa.Column('speed', sa.Integer(), nullable=True),
    sa.Column('life_steal', sa.Integer(), nullable=True),
    sa.Column('spell_vamp', sa.Integer(), nullable=True),
    sa.Column('is_watching', sa.Boolean(), nullable=True),
    sa.Column('start_watch', sa.DateTime(), nullable=True),
    sa.Column('title_id', sa.Integer(), nullable=True),
    sa.Column('player_shop_id', sa.Integer(), nullable=True),
    sa.Column('shop_level', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_login', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['player_shop_id'], ['player_shop.player_shop_id'], ),
    sa.ForeignKeyConstraint(['title_id'], ['titles.title_id'], ),
    sa.PrimaryKeyConstraint('player_id'),
    sa.UniqueConstraint('username')
    )
    op.create_index(op.f('ix_players_player_id'), 'players', ['player_id'], unique=False)
    op.create_index(op.f('ix_players_twitch_id'), 'players', ['twitch_id'], unique=True)
    op.create_table('spells',
    sa.Column('spell_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('weapon_id', sa.Integer(), nullable=True),
    sa.Column('damage_type', sa.Enum('PHYSICAL', 'MAGICAL', 'TRUE', 'HEALING', name='damagetype'), nullable=False),
    sa.Column('mana_cost', sa.Integer(), nullable=True),
    sa.Column('echo_cost', sa.Integer(), nullable=True),
    sa.Column('cooldown', sa.Integer(), nullable=True),
    sa.Column('effects', sa.JSON(), nullable=False),
    sa.ForeignKeyConstraint(['weapon_id'], ['weapons.weapon_id'], ),
    sa.PrimaryKeyConstraint('spell_id')
    )
    op.create_index(op.f('ix_spells_spell_id'), 'spells', ['spell_id'], unique=False)
    op.create_table('inventories',
    sa.Column('inventory_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('player_id', sa.Integer(), nullable=False),
    sa.Column('item_id', sa.Integer(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['item_id'], ['items.item_id'], ),
    sa.ForeignKeyConstraint(['player_id'], ['players.player_id'], ),
    sa.PrimaryKeyConstraint('inventory_id')
    )
    op.create_index(op.f('ix_inventories_inventory_id'), 'inventories', ['inventory_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_inventories_inventory_id'), table_name='inventories')
    op.drop_table('inventories')
    op.drop_index(op.f('ix_spells_spell_id'), table_name='spells')
    op.drop_table('spells')
    op.drop_index(op.f('ix_players_twitch_id'), table_name='players')
    op.drop_index(op.f('ix_players_player_id'), table_name='players')
    op.drop_table('players')
    op.drop_index(op.f('ix_weapons_weapon_id'), table_name='weapons')
    op.drop_table('weapons')
    op.drop_index(op.f('ix_titles_title_id'), table_name='titles')
    op.drop_table('titles')
    op.drop_index(op.f('ix_quests_quest_id'), table_name='quests')
    op.drop_table('quests')
    op.drop_index(op.f('ix_player_shop_player_shop_id'), table_name='player_shop')
    op.drop_table('player_shop')
    op.drop_index(op.f('ix_monsters_monster_id'), table_name='monsters')
    op.drop_table('monsters')
    op.drop_index(op.f('ix_items_item_id'), table_name='items')
    op.drop_table('items')
    # ### end Alembic commands ###
