"""Inventory equipped_slot and remove legacy equipement

Revision ID: c994f132fa10
Revises: 4cf0a9f6aece
Create Date: 2026-03-01 17:45:58.603611

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'c994f132fa10'
down_revision: Union[str, None] = '4cf0a9f6aece'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_player_stats_id'), table_name='player_stats')
    op.drop_index(op.f('ix_player_stats_player_id'), table_name='player_stats')
    op.drop_table('player_stats')
    op.drop_index(op.f('ix_spells_spell_id'), table_name='spells')
    op.drop_table('spells')
    op.drop_index(op.f('ix_effects_effect_id'), table_name='effects')
    op.drop_index(op.f('ix_effects_id'), table_name='effects')
    op.drop_index(op.f('ix_effects_item_id'), table_name='effects')
    op.drop_table('effects')
    op.drop_index(op.f('ix_item_stats_id'), table_name='item_stats')
    op.drop_index(op.f('ix_item_stats_item_id'), table_name='item_stats')
    op.drop_table('item_stats')
    op.drop_index(op.f('ix_weapons_weapon_id'), table_name='weapons')
    op.drop_table('weapons')
    op.drop_index(op.f('ix_items_item_id'), table_name='items')
    op.drop_constraint(op.f('inventories_item_id_fkey'), 'inventories', type_='foreignkey')
    op.drop_table('items')
    op.add_column('inventories', sa.Column('equipped_slot', sa.String(length=50), nullable=True))
    op.alter_column('inventories', 'item_id',
               existing_type=sa.INTEGER(),
               type_=sa.String(length=100),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(op.f('inventories_item_id_fkey'), 'inventories', 'items', ['item_id'], ['item_id'])
    op.alter_column('inventories', 'item_id',
               existing_type=sa.String(length=100),
               type_=sa.INTEGER(),
               existing_nullable=False)
    op.drop_column('inventories', 'equipped_slot')
    op.create_table('items',
    sa.Column('item_id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('description', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('rarity', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('item_type', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('value', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('item_id', name=op.f('items_pkey'))
    )
    op.create_index(op.f('ix_items_item_id'), 'items', ['item_id'], unique=False)
    op.create_table('weapons',
    sa.Column('weapon_id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('bonus_ad', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('bonus_ap', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('bonus_speed', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('weapon_id', name=op.f('weapons_pkey'))
    )
    op.create_index(op.f('ix_weapons_weapon_id'), 'weapons', ['weapon_id'], unique=False)
    op.create_table('item_stats',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('item_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('hp', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('ad', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('ap', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('adaptive_force', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('armor', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('magic_resist', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('speed_flat', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('crit_chance_percent', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('life_steal_percent', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('spell_vamp_percent', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('item_stats_pkey'))
    )
    op.create_index(op.f('ix_item_stats_item_id'), 'item_stats', ['item_id'], unique=False)
    op.create_index(op.f('ix_item_stats_id'), 'item_stats', ['id'], unique=False)
    op.create_table('effects',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('effect_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('item_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('ad_base_dmg', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('ap_base_dmg', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('ad_ratio', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('ap_ratio', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('hp_ratio', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('armor_ratio', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('mr_ratio', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('crit_ratio', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('speed_ratio', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('effects_pkey'))
    )
    op.create_index(op.f('ix_effects_item_id'), 'effects', ['item_id'], unique=False)
    op.create_index(op.f('ix_effects_id'), 'effects', ['id'], unique=False)
    op.create_index(op.f('ix_effects_effect_id'), 'effects', ['effect_id'], unique=False)
    op.create_table('spells',
    sa.Column('spell_id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('description', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('weapon_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('damage_type', postgresql.ENUM('PHYSICAL', 'MAGICAL', 'TRUE', 'HEALING', name='damagetype'), autoincrement=False, nullable=False),
    sa.Column('mana_cost', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('echo_cost', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('cooldown', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('effects', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['weapon_id'], ['weapons.weapon_id'], name=op.f('spells_weapon_id_fkey')),
    sa.PrimaryKeyConstraint('spell_id', name=op.f('spells_pkey'))
    )
    op.create_index(op.f('ix_spells_spell_id'), 'spells', ['spell_id'], unique=False)
    op.create_table('player_stats',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('player_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('hp_flat', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('hp_percent', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('ad', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('ap', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('armor', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('magic_resist', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('speed_flat', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('speed_percent', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('crit_rate_percent', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('penetration_flat', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('penetration_percent', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('final_damage_dealt_percent', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('on_hit_damage_flat', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('damage_reduction_percent', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('damage_reduction_flat', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('heal_shield_power_percent', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('echo_gauge_percent', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('berserk_stats_percent', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('player_stats_pkey'))
    )
    op.create_index(op.f('ix_player_stats_player_id'), 'player_stats', ['player_id'], unique=False)
    op.create_index(op.f('ix_player_stats_id'), 'player_stats', ['id'], unique=False)
    # ### end Alembic commands ###
